version: "3"

services:
  app:
    build: .
    container_name: tus_dev_app
    depends_on:
      - mongodb
    volumes:
     - .:/app
    ports:
      - "5000:5000"

    environment:
      DB_NAME: tus_dev
      DB_HOST: mongodb
      DB_PORT: 27017
      FLASK_APP: /app/example/app.py

  mongodb:
    image: mongo:3.7.7
    restart: always
    container_name: tus_dev_mongo
    ports:
      - "27017:27017"
    environment:
      TZ: Europe/Copenhagen
    tmpfs: /data/db
