version: "3"

services:
  app:
    build: .
    image: volesen/tus
    container_name: tus_dev_app
    command: ash scripts/startup_app.sh
    depends_on:
      - mongodb
    volumes:
     - .:/app
    ports:
      - "5000:80"

    environment:
      DB_NAME: tus_dev
      DB_HOST: mongodb
      DB_PORT: 27017
      FLASK_APP: /app/demo/app.py

  mongodb:
    image: mongo:3.7.7
    restart: always
    container_name: tus_dev_mongo
    environment:
      TZ: Europe/Copenhagen
    volumes:
      - ./storage/permastore/mongo:/data/db
